title:        alixedi
tagline:      'Hyde, a Jekyll theme'
description:  'Generalist / Entrepreneur / Full-stack Developer.'
url:          http://alixedi.github.io
version:      1.1.1
author:
  name:       'Ali Zaidi'
  email:      'alixedi@gmail.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
