title:            alixedi
description:      Books | Software | Life
url:              http://alixedi.github.io
signoff:          Ali Zaidi
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
google_analytics: UA-50156139-2

links:
  - name:         About
    url:          /about
  - name:         Twitter
    url:          http://twitter.com/alixedi
    external:     true
  - name:         GitHub
    url:          http://github.com/alixedi
    external:     true
pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
