# Site settings
title: "alixedi"
description: "I make stuff."
baseurl: ""
url: "http://alixedi.github.io"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments

# Links
links:
  - title: "About"
    url: /about
  - title: "Twitter"
    url: http://twitter.com/alixedi
  - title: "Github"
    url: http://github.com/alixedi
  - title: "RSS"
    url: /feed.xml
